## Objective:

Load data, perform basic calculations and use NumPys array manipulatin capabilities

##Load Data

If your data is numeric, you can load your file with the NumPy library.

The definition of the dataSet:
* Col0: 'MathScores'
* Col1: 'ScienceScores'
* Col2: 'HistoryScores'

In [ ]:
import numpy as np


In [ ]:
from google.colab import files

uploaded = files.upload()

for fn in uploaded.keys():
  print('User uploaded file "{name}" with length {length} bytes'.format(
      name=fn, length=len(uploaded[fn])))

Saving students_num.txt to students_num.txt
User uploaded file "students_num.txt" with length 185 bytes


In [ ]:
#You can define the delimiter, and pass the tuple with the columns you expect
np.loadtxt('students_num.txt',delimiter=',',skiprows=1,usecols=(0,2))

array([[ 7.,  9.],
       [10.,  8.],
       [10.,  7.],
       [ 6., 10.],
       [ 8.,  7.],
       [ 8.,  7.],
       [ 9.,  9.],
       [ 7., 10.],
       [ 7., 10.],
       [ 6., 10.],
       [ 8., 10.],
       [ 6.,  9.],
       [ 7.,  8.],
       [ 8.,  7.],
       [ 7.,  8.],
       [ 9.,  9.],
       [ 6., 10.],
       [ 9.,  7.],
       [ 9.,  9.],
       [ 8.,  9.]])

In [ ]:
#Load data and asign
data = np.loadtxt('students_num.txt',delimiter=',',skiprows=1)

In [ ]:
len(data)

20

In [ ]:
np.shape(data)

(20, 3)

In [ ]:
data

array([[ 7.,  9.,  9.],
       [10.,  6.,  8.],
       [10.,  9.,  7.],
       [ 6.,  6., 10.],
       [ 8.,  6.,  7.],
       [ 8.,  9.,  7.],
       [ 9.,  7.,  9.],
       [ 7.,  5., 10.],
       [ 7.,  6., 10.],
       [ 6.,  9., 10.],
       [ 8.,  7., 10.],
       [ 6.,  5.,  9.],
       [ 7.,  8.,  8.],
       [ 8.,  6.,  7.],
       [ 7.,  9.,  8.],
       [ 9.,  9.,  9.],
       [ 6.,  9., 10.],
       [ 9.,  6.,  7.],
       [ 9.,  6.,  9.],
       [ 8.,  8.,  9.]])

In [ ]:
#Compute the average score of each subject

#Write your code here



array([7.75, 7.25, 8.65])

In [ ]:
#Get highest average score

#Write your code here



9.0

In [ ]:
#return the student index that got the highest score
#Write your code here


15

In [ ]:
# Get the lowest average score
# Write your code here



6.666666666666667

In [ ]:
#return the student index that got the lowest score
#Write your code here


11

In [ ]:
#Compute the overall average score across all students and all subjects.
#write your code here


7.883333333333334

# Part 2

In [ ]:
#Create a zeros vector of size of rows of the array data
# Write your code here

new_col =

In [ ]:
np.shape(new_col)

(20,)

In [ ]:
np.shape(data)

(20, 3)

In [ ]:
#Create a new column that represents the total score for each student (sum of scores in all subjects).

In [ ]:
data_newcol = np.concatenate((data,np.reshape(new_col,(20,1))),axis=1) #Notice that we have to reshape new_col to concatenate arrays

In [ ]:
#Asign to the new col the sum of all scores for each student
# Write your code here
data_newcol[:,3] =

In [ ]:
#Normalize the scores for each student by dividing each subject's score by the maximum score in that subject.
#Write your code here

max_scores =
print(max_scores)


[10.  9. 10.]


In [ ]:
#Divide all data set and max_scores
#Write your code here


array([[0.7       , 1.        , 0.9       ],
       [1.        , 0.66666667, 0.8       ],
       [1.        , 1.        , 0.7       ],
       [0.6       , 0.66666667, 1.        ],
       [0.8       , 0.66666667, 0.7       ],
       [0.8       , 1.        , 0.7       ],
       [0.9       , 0.77777778, 0.9       ],
       [0.7       , 0.55555556, 1.        ],
       [0.7       , 0.66666667, 1.        ],
       [0.6       , 1.        , 1.        ],
       [0.8       , 0.77777778, 1.        ],
       [0.6       , 0.55555556, 0.9       ],
       [0.7       , 0.88888889, 0.8       ],
       [0.8       , 0.66666667, 0.7       ],
       [0.7       , 1.        , 0.8       ],
       [0.9       , 1.        , 0.9       ],
       [0.6       , 1.        , 1.        ],
       [0.9       , 0.66666667, 0.7       ],
       [0.9       , 0.66666667, 0.9       ],
       [0.8       , 0.88888889, 0.9       ]])

#Rank and Sorting

```np.sort``` Return a sorted copy of an array

In [ ]:
np.sort(data, axis=0) # sort entire column

array([[ 6.,  5.,  7.],
       [ 6.,  5.,  7.],
       [ 6.,  6.,  7.],
       [ 6.,  6.,  7.],
       [ 7.,  6.,  7.],
       [ 7.,  6.,  8.],
       [ 7.,  6.,  8.],
       [ 7.,  6.,  8.],
       [ 7.,  6.,  9.],
       [ 8.,  7.,  9.],
       [ 8.,  7.,  9.],
       [ 8.,  8.,  9.],
       [ 8.,  8.,  9.],
       [ 8.,  9.,  9.],
       [ 9.,  9., 10.],
       [ 9.,  9., 10.],
       [ 9.,  9., 10.],
       [ 9.,  9., 10.],
       [10.,  9., 10.],
       [10.,  9., 10.]])

In [ ]:
np.sort(data,axis=1) # sort entire row

array([[ 7.,  9.,  9.],
       [ 6.,  8., 10.],
       [ 7.,  9., 10.],
       [ 6.,  6., 10.],
       [ 6.,  7.,  8.],
       [ 7.,  8.,  9.],
       [ 7.,  9.,  9.],
       [ 5.,  7., 10.],
       [ 6.,  7., 10.],
       [ 6.,  9., 10.],
       [ 7.,  8., 10.],
       [ 5.,  6.,  9.],
       [ 7.,  8.,  8.],
       [ 6.,  7.,  8.],
       [ 7.,  8.,  9.],
       [ 9.,  9.,  9.],
       [ 6.,  9., 10.],
       [ 6.,  7.,  9.],
       [ 6.,  9.,  9.],
       [ 8.,  8.,  9.]])

In [ ]:
#sort students based on their science score in descending order
np.sort(data[:,1]) [::-1] #Get the reversed array

array([9., 9., 9., 9., 9., 9., 9., 8., 8., 7., 7., 6., 6., 6., 6., 6., 6.,
       6., 5., 5.])

In [ ]:
np.flip(np.sort(data[:,1]) ) # Other form to get the reverse

array([9., 9., 9., 9., 9., 9., 9., 8., 8., 7., 7., 6., 6., 6., 6., 6., 6.,
       6., 5., 5.])

In [ ]:
data[:,1]

array([9., 6., 9., 6., 6., 9., 7., 5., 6., 9., 7., 5., 8., 6., 9., 9., 9.,
       6., 6., 8.])

In [ ]:
# Get the indexes of students based on their science score in descending order

The function ```np.argsort(data)``` return the indexes of the sorted array

In [ ]:
np.argsort(data[:,1])

array([12,  8,  1,  2, 16, 15,  6, 18, 11,  9, 13,  0,  7,  5, 14,  4,  3,
       17, 10, 19])

You can concatenate two arrays as long as the dimensions match.

For example if we wanto to concatenate a vector 1-D and a 2-D matrix, the vector must be reshaped as as 2-D matrix of 1 single column

In [ ]:
# Concatenate
np.concatenate(((np.argsort(data[:,1])).reshape((20,-1)),(np.sort(data[:,1])).reshape((20,-1))),axis=1)

array([[ 7.,  5.],
       [11.,  5.],
       [ 1.,  6.],
       [17.,  6.],
       [ 3.,  6.],
       [ 4.,  6.],
       [ 8.,  6.],
       [18.,  6.],
       [13.,  6.],
       [ 6.,  7.],
       [10.,  7.],
       [19.,  8.],
       [12.,  8.],
       [16.,  9.],
       [15.,  9.],
       [ 0.,  9.],
       [ 5.,  9.],
       [ 2.,  9.],
       [14.,  9.],
       [ 9.,  9.]])

With NumPy, you can inspect the values that satisfy the condition

In [ ]:

data[data[:,1]>8,1] #return all values exceed condition

Function ```where()``` return an array that satisfies the condition:
```
  >>> a = np.arange(10)
  >>> a
  array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
  >>> np.where(a < 5, a, 10*a)
  array([ 0,  1,  2,  3,  4, 50, 60, 70, 80, 90])
```

In [ ]:
np.where(data[:,1]>8) # Get the indices

In [ ]:
data[:,1]

array([9., 6., 9., 6., 6., 9., 7., 5., 6., 9., 7., 5., 8., 6., 9., 9., 9.,
       6., 6., 8.])

# Split NumPy array


In [ ]:
#with random.permutation, return a shuffled array from 0 to n-1
shuffled_indices = np.random.permutation(len(data))

In [ ]:
shuffled_indices

array([ 8,  6, 13, 11, 10,  2,  3, 12, 14,  1, 19, 17,  9,  0,  5, 15, 18,
       16,  7,  4])

In [ ]:
test_set_size = int(len(data)*0.2)
test_set_size

4

In [ ]:
test_indices = shuffled_indices[:test_set_size]
test_indices

array([ 8,  6, 13, 11])

In [ ]:
train_indices = shuffled_indices[test_set_size:]
train_indices

array([10,  2,  3, 12, 14,  1, 19, 17,  9,  0,  5, 15, 18, 16,  7,  4])

In [ ]:
x_train = data[train_indices,:]
x_train

array([[ 8.,  7., 10.],
       [10.,  9.,  7.],
       [ 6.,  6., 10.],
       [ 7.,  8.,  8.],
       [ 7.,  9.,  8.],
       [10.,  6.,  8.],
       [ 8.,  8.,  9.],
       [ 9.,  6.,  7.],
       [ 6.,  9., 10.],
       [ 7.,  9.,  9.],
       [ 8.,  9.,  7.],
       [ 9.,  9.,  9.],
       [ 9.,  6.,  9.],
       [ 6.,  9., 10.],
       [ 7.,  5., 10.],
       [ 8.,  6.,  7.]])

In [ ]:
x_test= data[test_indices,:]
x_test

array([[ 7.,  6., 10.],
       [ 9.,  7.,  9.],
       [ 8.,  6.,  7.],
       [ 6.,  5.,  9.]])

In [ ]:
#Define a function that takes the data and return a dataset for training and other for test
#test_ratio defines the percentage of the size of the test dataset.
def split_train_test(data,test_ratio):
  shuffled_indices = np.random.permutation(len(data))
  test_set_size = int(len(data) * test_ratio)
  test_indices = shuffled_indices[:test_set_size]
  train_indices = shuffled_indices[test_set_size:]
  return data[train_indices,:], data[test_indices,:]

In [ ]:
train,test=split_train_test(data,0.1)

In [ ]:
test

array([[ 8.,  7., 10.],
       [10.,  6.,  8.]])