# Exercise

Instructions:

1. Load DataSet as DataFame.

2. Create DF X_data from columns:"longitude","latitude","housing_median_age","total_rooms","total_bedrooms","population","households","median_income","ocean_proximity".
Create y_data with column "median_house_value"


3. Replace NaN values with mean method

4. Create a new column called "rooms_per_household" defined as the ratio between the "total_rooms" and "households".

5. Create a new_column called "bedrooms_per_room" defined as the ratio between "total_bedrooms" and "total_rooms".

6. Create a new column called "population_per_household" defined as the ratio between "population" and "households".

7. Asign a int value for every category in the "ocean_proximity":

  "<1H OCEAN" -> 1,
  "NEAR OCEAN"-> 2,
  ...

8.  Transform the X_data with the complete numeric data as a NumPy Array.


9. Apply min-max for all columns except the ocean_proximity column.

$min$_$max$ = $X-min/(max-min)$
10. Split in train and test for X_data and y_data with test_ratio = 0.2


# Step 1. Load Data

In [124]:
import pandas as pd
import numpy as np

In [125]:
# Write your code
# Load the housing.csv file
df = pd.DataFrame(pd.read_csv('housing.csv'))
df.head(5)

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -122.23     37.88                41.0        880.0           129.0   
1    -122.22     37.86                21.0       7099.0          1106.0   
2    -122.24     37.85                52.0       1467.0           190.0   
3    -122.25     37.85                52.0       1274.0           235.0   
4    -122.25     37.85                52.0       1627.0           280.0   

   population  households  median_income  median_house_value ocean_proximity  
0       322.0       126.0         8.3252            452600.0        NEAR BAY  
1      2401.0      1138.0         8.3014            358500.0        NEAR BAY  
2       496.0       177.0         7.2574            352100.0        NEAR BAY  
3       558.0       219.0         5.6431            341300.0        NEAR BAY  
4       565.0       259.0         3.8462            342200.0        NEAR BAY

In [126]:
# Create DF X_data from columns:"longitude","latitude","housing_median_age","total_rooms","total_bedrooms","population","households","median_income","ocean_proximity".
X_data = pd.DataFrame(df, columns=["longitude","latitude","housing_median_age","total_rooms","total_bedrooms","population","households","median_income","ocean_proximity"])
X_data

# Create y_data with column "median_house_value"
y_data = pd.DataFrame(df, columns=["median_house_value"])

In [127]:
df.head(2)

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -122.23     37.88                41.0        880.0           129.0   
1    -122.22     37.86                21.0       7099.0          1106.0   

   population  households  median_income  median_house_value ocean_proximity  
0       322.0       126.0         8.3252            452600.0        NEAR BAY  
1      2401.0      1138.0         8.3014            358500.0        NEAR BAY

# Step 2. Create X_data

In [128]:
X_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20640 entries, 0 to 20639
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   longitude           20640 non-null  float64
 1   latitude            20640 non-null  float64
 2   housing_median_age  20640 non-null  float64
 3   total_rooms         20640 non-null  float64
 4   total_bedrooms      20433 non-null  float64
 5   population          20640 non-null  float64
 6   households          20640 non-null  float64
 7   median_income       20640 non-null  float64
 8   ocean_proximity     20640 non-null  object 
dtypes: float64(8), object(1)
memory usage: 1.4+ MB


#Step 3. Fill Nan values with mean

In [129]:
#Compute the mean
#Write your code here

#mean = np.mean(X_data['total_bedrooms'], axis=0)
mean = X_data['total_bedrooms'].mean()

#Fill NaN values, remember inplace = True
#Write your code here
## Dealing with empty data
X_data['total_bedrooms'].fillna(mean,inplace=True)

In [130]:
X_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20640 entries, 0 to 20639
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   longitude           20640 non-null  float64
 1   latitude            20640 non-null  float64
 2   housing_median_age  20640 non-null  float64
 3   total_rooms         20640 non-null  float64
 4   total_bedrooms      20640 non-null  float64
 5   population          20640 non-null  float64
 6   households          20640 non-null  float64
 7   median_income       20640 non-null  float64
 8   ocean_proximity     20640 non-null  object 
dtypes: float64(8), object(1)
memory usage: 1.4+ MB


# Step 4,5,6. Creation of new columns

In [131]:
#Create new columns in X_data
# Create a new column called "rooms_per_household" defined as the ratio between the "total_rooms" and "households".

# Create a new_column called "bedrooms_per_room" defined as the ratio between "total_bedrooms" and "total_rooms".

# Create a new column called "population_per_household" defined as the ratio between "population" and "households".
X_data["rooms_per_household"] = X_data['total_rooms'] / X_data['households']
X_data["bedrooms_per_room"] = X_data['total_bedrooms'] / X_data['total_rooms']
X_data["population_per_household"]= X_data['population'] / X_data['households']

In [47]:
X_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20640 entries, 0 to 20639
Data columns (total 12 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   longitude                 20640 non-null  float64
 1   latitude                  20640 non-null  float64
 2   housing_median_age        20640 non-null  float64
 3   total_rooms               20640 non-null  float64
 4   total_bedrooms            20640 non-null  float64
 5   population                20640 non-null  float64
 6   households                20640 non-null  float64
 7   median_income             20640 non-null  float64
 8   ocean_proximity           20640 non-null  object 
 9   rooms_per_household       20640 non-null  float64
 10  bedrooms_per_room         20640 non-null  float64
 11  population_per_household  20640 non-null  float64
dtypes: float64(11), object(1)
memory usage: 1.9+ MB


# Step 7. Transform to numeric categoritc Data

In [132]:
X_data['ocean_proximity'].unique()

array(['NEAR BAY', '<1H OCEAN', 'INLAND', 'NEAR OCEAN', 'ISLAND'],
      dtype=object)

In [133]:
mapping = {'NEAR BAY':1, '<1H OCEAN':2, 'INLAND':3, 'NEAR OCEAN':4, 'ISLAND':5}

In [134]:
X_data.replace({'ocean_proximity': mapping},inplace=True)

In [106]:
X_data.tail()

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
20635    -121.09     39.48                25.0       1665.0           374.0   
20636    -121.21     39.49                18.0        697.0           150.0   
20637    -121.22     39.43                17.0       2254.0           485.0   
20638    -121.32     39.43                18.0       1860.0           409.0   
20639    -121.24     39.37                16.0       2785.0           616.0   

       population  households  median_income  ocean_proximity  
20635       845.0       330.0         1.5603                3  
20636       356.0       114.0         2.5568                3  
20637      1007.0       433.0         1.7000                3  
20638       741.0       349.0         1.8672                3  
20639      1387.0       530.0         2.3886                3

# Step 8. Transform to NumPy array

In [135]:
# Transform the X_data with the complete numeric data as a NumPy Array.
# Convert the numeric data X_data to numpy array
X_array = X_data.to_numpy()
X_array

array([[-122.23      ,   37.88      ,   41.        , ...,    6.98412698,
           0.14659091,    2.55555556],
       [-122.22      ,   37.86      ,   21.        , ...,    6.23813708,
           0.15579659,    2.10984183],
       [-122.24      ,   37.85      ,   52.        , ...,    8.28813559,
           0.12951602,    2.80225989],
       ...,
       [-121.22      ,   39.43      ,   17.        , ...,    5.20554273,
           0.21517303,    2.3256351 ],
       [-121.32      ,   39.43      ,   18.        , ...,    5.32951289,
           0.21989247,    2.12320917],
       [-121.24      ,   39.37      ,   16.        , ...,    5.25471698,
           0.22118492,    2.61698113]])

In [136]:
np.shape(X_array)

(20640, 12)

In [137]:
# Create the numpy array y_array of "median house values" column
y_array = y_data.to_numpy()

In [138]:
np.shape(y_array)

(20640, 1)

# Step 8. MinMax transformation
9. Apply min-max for all columns except the ocean_proximity column.

In [139]:
# Compute the max value per column
# Write your  code here
max_cols = np.max(X_array, axis=0)
max_cols

array([-1.14310000e+02,  4.19500000e+01,  5.20000000e+01,  3.93200000e+04,
        6.44500000e+03,  3.56820000e+04,  6.08200000e+03,  1.50001000e+01,
        5.00000000e+00,  1.41909091e+02,  3.49266593e+00,  1.24333333e+03])

In [140]:
# Create a zeros vector of size of rows of the array data
new_col =  np.zeros(X_array.shape[0])
new_col.shape

(20640,)

In [142]:
# Compute the min value per column
min_cols = np.min(X_array, axis=0)
min_cols

array([-1.24350000e+02,  3.25400000e+01,  1.00000000e+00,  2.00000000e+00,
        1.00000000e+00,  3.00000000e+00,  1.00000000e+00,  4.99900000e-01,
        1.00000000e+00,  8.46153846e-01,  4.59365063e-02,  6.92307692e-01])

$min$_$max$ = $X-min/(max-min)$

In [143]:
# Apply formula for X_array
min_max = (X_array - min_cols) / (max_cols - min_cols)
min_max

array([[0.21115538, 0.5674814 , 0.78431373, ..., 0.0435123 , 0.02920287,
        0.00149943],
       [0.21215139, 0.565356  , 0.39215686, ..., 0.03822395, 0.03187372,
        0.00114074],
       [0.21015936, 0.5642933 , 1.        , ..., 0.05275646, 0.02424893,
        0.00169796],
       ...,
       [0.31175299, 0.73219979, 0.31372549, ..., 0.03090386, 0.04910061,
        0.0013144 ],
       [0.30179283, 0.73219979, 0.33333333, ..., 0.03178269, 0.05046986,
        0.0011515 ],
       [0.30976096, 0.72582359, 0.29411765, ..., 0.03125246, 0.05084484,
        0.00154886]])

#Step 9. Return the X_train,y_train, X_test,y_test dataset

In [149]:
# Make function to split X and y arrays, remember the indexes must be the same for X and y
def split_train_test(X,y,test_ratio):
  shuffled_indices = np.random.permutation(len(X))
  test_set_size = int(len(X) * test_ratio)
  test_indices = shuffled_indices[:test_set_size]
  train_indices = shuffled_indices[test_set_size:]
  #Return X_train,X_test,y_train,y_test
  #Write your code here
  return X[train_indices, :], X[test_indices, :], y[train_indices], y[test_indices]

In [150]:
#Call function split_train_test
#Write your code here
X_train,X_test,y_train,y_test = split_train_test(X_array, y_array, 0.2)

In [151]:
np.shape(X_train)

(16512, 12)

In [152]:
np.shape(y_train)

(16512, 1)

In [153]:
np.shape(X_test)

(4128, 12)

In [154]:
np.shape(y_test)

(4128, 1)

# Congratulations, you can prove your dataset in a Machine Learning algorithm!!!