## Objective:

Load data, perform basic calculations and use NumPys array manipulatin capabilities

## Load Data

If your data is numeric, you can load your file with the NumPy library.

The definition of the dataSet:
* Col0: 'MathScores'
* Col1: 'ScienceScores'
* Col2: 'HistoryScores'

In [1]:
import numpy as np

In [ ]:
# from google.colab import files

# uploaded = files.upload()

for fn in uploaded.keys():
  print('User uploaded file "{name}" with length {length} bytes'.format(
      name=fn, length=len(uploaded[fn])))

Saving students_num.txt to students_num.txt
User uploaded file "students_num.txt" with length 185 bytes


In [2]:
# 'students_num.txt': This is the name of the text file from which you want to load data. Make sure the file is present in the current working directory or provide the full file path if it's located elsewhere.

# delimiter=',': This argument specifies the delimiter used in the text file to separate values. In this case, a comma (',') is used as the delimiter. It means that the values in each row of the file are separated by commas.

# skiprows=1: This argument indicates the number of rows to skip while loading data from the text file. In this case, it's set to 1, which means the first row (usually header) will be skipped. Data loading will start from the second row.

# usecols=(0,2): This argument specifies which columns from the text file should be loaded. It's a tuple containing column indices (0-based) that you want to include in the loaded data. In this case, columns 0 and 2 will be loaded. This means the first and third columns (remember, Python uses 0-based indexing) of the data in each row will be extracted.

# In summary, this line of code reads numerical data from the file 'students_num.txt', where the values are separated by commas, skips the header row, and loads only the values from the first and third columns into a NumPy array.

# You can define the delimiter, and pass the tuple with the columns you expect
np.loadtxt('students_num.txt', delimiter=',',skiprows=1, usecols=(0,2))

array([[ 7.,  9.],
       [10.,  8.],
       [10.,  7.],
       [ 6., 10.],
       [ 8.,  7.],
       [ 8.,  7.],
       [ 9.,  9.],
       [ 7., 10.],
       [ 7., 10.],
       [ 6., 10.],
       [ 8., 10.],
       [ 6.,  9.],
       [ 7.,  8.],
       [ 8.,  7.],
       [ 7.,  8.],
       [ 9.,  9.],
       [ 6., 10.],
       [ 9.,  7.],
       [ 9.,  9.],
       [ 8.,  9.]])

In [3]:
#Load data and asign
data = np.loadtxt('students_num.txt',delimiter=',',skiprows=1)

In [4]:
len(data)

20

In [5]:
np.shape(data)

(20, 3)

In [ ]:
data

array([[ 7.,  9.,  9.],
       [10.,  6.,  8.],
       [10.,  9.,  7.],
       [ 6.,  6., 10.],
       [ 8.,  6.,  7.],
       [ 8.,  9.,  7.],
       [ 9.,  7.,  9.],
       [ 7.,  5., 10.],
       [ 7.,  6., 10.],
       [ 6.,  9., 10.],
       [ 8.,  7., 10.],
       [ 6.,  5.,  9.],
       [ 7.,  8.,  8.],
       [ 8.,  6.,  7.],
       [ 7.,  9.,  8.],
       [ 9.,  9.,  9.],
       [ 6.,  9., 10.],
       [ 9.,  6.,  7.],
       [ 9.,  6.,  9.],
       [ 8.,  8.,  9.]])

In [11]:
# Compute the average score of each subject

# Write your code here
ex1 = np.mean(data, axis=0)
ex1

array([7.75, 7.25, 8.65])

In [12]:
#Get highest average score

#Write your code here
ex1.max()

8.65

In [53]:
#return the student index that got the highest score
def find_index(m):
     if (m == 'M'):
          max = data.max(axis=0).max()
          
          for n in range(data.shape[0]):
               if data[n].max() == max:
                    print(n)
                    break
     elif (m == 'm'):
          min = data.min(axis=0).min()
          
          for n in range(data.shape[0]):
               if data[n].min() == min:
                    print(n)
                    break

find_index('M')

1


In [19]:
# Get the lowest average score
# Write your code here
ex1.min()

7.25

In [54]:
#return the student index that got the lowest score
#Write your code here
find_index('m')

7


In [56]:
#Compute the overall average score across all students and all subjects.
#write your code here
np.mean(data)

array([7.75, 7.25, 8.65])

# Part 2

In [77]:
# Create a zeros vector of size of rows of the array data
# Write your code here
new_col =  np.zeros(data.shape[0])
new_col

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.])

In [78]:
np.shape(new_col)

(20,)

In [79]:
np.shape(data)

(20, 3)

In [80]:
new_col = np.mean(data[:,:])
new_col

7.883333333333334

In [81]:
# Nota de clase: One code encoding: por ejemplo, tenemos 3 categorías: {D: 1, V:2, A: 3} 
# entonces tendríamos {[0,0,1], [0,1,0], [1,0,0]}

# Create a new column that represents the total score for each student 
# (sum of scores in all subjects).
total_score = []
for n in range(data.shape[0]):
     total_score.append(np.sum(data[n], axis=0))

total_score

[25.0,
 24.0,
 26.0,
 22.0,
 21.0,
 24.0,
 25.0,
 22.0,
 23.0,
 25.0,
 25.0,
 20.0,
 23.0,
 21.0,
 24.0,
 27.0,
 25.0,
 22.0,
 24.0,
 25.0]

In [71]:
data_newcol = np.concatenate((data,np.reshape(total_score,(20,1))),axis=1) #Notice that we have to reshape new_col to concatenate arrays
data_newcol

array([[ 7.,  9.,  9., 25.],
       [10.,  6.,  8., 24.],
       [10.,  9.,  7., 26.],
       [ 6.,  6., 10., 22.],
       [ 8.,  6.,  7., 21.],
       [ 8.,  9.,  7., 24.],
       [ 9.,  7.,  9., 25.],
       [ 7.,  5., 10., 22.],
       [ 7.,  6., 10., 23.],
       [ 6.,  9., 10., 25.],
       [ 8.,  7., 10., 25.],
       [ 6.,  5.,  9., 20.],
       [ 7.,  8.,  8., 23.],
       [ 8.,  6.,  7., 21.],
       [ 7.,  9.,  8., 24.],
       [ 9.,  9.,  9., 27.],
       [ 6.,  9., 10., 25.],
       [ 9.,  6.,  7., 22.],
       [ 9.,  6.,  9., 24.],
       [ 8.,  8.,  9., 25.]])

In [75]:
# Asign to the new col the sum of all scores for each student
# Write your code here
data_newcol[:,3] = new_col
data_newcol

array([[ 7.        ,  9.        ,  9.        ,  7.88333333],
       [10.        ,  6.        ,  8.        ,  7.88333333],
       [10.        ,  9.        ,  7.        ,  7.88333333],
       [ 6.        ,  6.        , 10.        ,  7.88333333],
       [ 8.        ,  6.        ,  7.        ,  7.88333333],
       [ 8.        ,  9.        ,  7.        ,  7.88333333],
       [ 9.        ,  7.        ,  9.        ,  7.88333333],
       [ 7.        ,  5.        , 10.        ,  7.88333333],
       [ 7.        ,  6.        , 10.        ,  7.88333333],
       [ 6.        ,  9.        , 10.        ,  7.88333333],
       [ 8.        ,  7.        , 10.        ,  7.88333333],
       [ 6.        ,  5.        ,  9.        ,  7.88333333],
       [ 7.        ,  8.        ,  8.        ,  7.88333333],
       [ 8.        ,  6.        ,  7.        ,  7.88333333],
       [ 7.        ,  9.        ,  8.        ,  7.88333333],
       [ 9.        ,  9.        ,  9.        ,  7.88333333],
       [ 6.        ,  9.

In [82]:
#Normalize the scores for each student by dividing each subject's score by the maximum score in that subject.
#Write your code here

max_scores = np.max(data[:,:], axis=1)
print(max_scores)


[ 9. 10. 10. 10.  8.  9.  9. 10. 10. 10. 10.  9.  8.  8.  9.  9. 10.  9.
  9.  9.]


In [87]:
#Divide all data set and max_scores
#Write your code here
np.divide(data[:,1], max_scores)
np.divide(data[:,2], max_scores)
np.divide(data[:,2], max_scores)

array([1.        , 0.8       , 0.7       , 1.        , 0.875     ,
       0.77777778, 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 0.875     , 0.88888889,
       1.        , 1.        , 0.77777778, 1.        , 1.        ])

#Rank and Sorting

```np.sort``` Return a sorted copy of an array

In [ ]:
np.sort(data, axis=0) # sort entire column

array([[ 6.,  5.,  7.],
       [ 6.,  5.,  7.],
       [ 6.,  6.,  7.],
       [ 6.,  6.,  7.],
       [ 7.,  6.,  7.],
       [ 7.,  6.,  8.],
       [ 7.,  6.,  8.],
       [ 7.,  6.,  8.],
       [ 7.,  6.,  9.],
       [ 8.,  7.,  9.],
       [ 8.,  7.,  9.],
       [ 8.,  8.,  9.],
       [ 8.,  8.,  9.],
       [ 8.,  9.,  9.],
       [ 9.,  9., 10.],
       [ 9.,  9., 10.],
       [ 9.,  9., 10.],
       [ 9.,  9., 10.],
       [10.,  9., 10.],
       [10.,  9., 10.]])

In [ ]:
np.sort(data,axis=1) # sort entire row

array([[ 7.,  9.,  9.],
       [ 6.,  8., 10.],
       [ 7.,  9., 10.],
       [ 6.,  6., 10.],
       [ 6.,  7.,  8.],
       [ 7.,  8.,  9.],
       [ 7.,  9.,  9.],
       [ 5.,  7., 10.],
       [ 6.,  7., 10.],
       [ 6.,  9., 10.],
       [ 7.,  8., 10.],
       [ 5.,  6.,  9.],
       [ 7.,  8.,  8.],
       [ 6.,  7.,  8.],
       [ 7.,  8.,  9.],
       [ 9.,  9.,  9.],
       [ 6.,  9., 10.],
       [ 6.,  7.,  9.],
       [ 6.,  9.,  9.],
       [ 8.,  8.,  9.]])

In [ ]:
#sort students based on their science score in descending order
np.sort(data[:,1]) [::-1] #Get the reversed array

array([9., 9., 9., 9., 9., 9., 9., 8., 8., 7., 7., 6., 6., 6., 6., 6., 6.,
       6., 5., 5.])

In [ ]:
np.flip(np.sort(data[:,1]) ) # Other form to get the reverse

array([9., 9., 9., 9., 9., 9., 9., 8., 8., 7., 7., 6., 6., 6., 6., 6., 6.,
       6., 5., 5.])

In [ ]:
data[:,1]

array([9., 6., 9., 6., 6., 9., 7., 5., 6., 9., 7., 5., 8., 6., 9., 9., 9.,
       6., 6., 8.])

In [ ]:
# Get the indexes of students based on their science score in descending order

The function ```np.argsort(data)``` return the indexes of the sorted array

In [ ]:
np.argsort(data[:,1])

array([12,  8,  1,  2, 16, 15,  6, 18, 11,  9, 13,  0,  7,  5, 14,  4,  3,
       17, 10, 19])

You can concatenate two arrays as long as the dimensions match.

For example if we wanto to concatenate a vector 1-D and a 2-D matrix, the vector must be reshaped as as 2-D matrix of 1 single column

In [ ]:
# Concatenate
np.concatenate(((np.argsort(data[:,1])).reshape((20,-1)),(np.sort(data[:,1])).reshape((20,-1))),axis=1)

array([[ 7.,  5.],
       [11.,  5.],
       [ 1.,  6.],
       [17.,  6.],
       [ 3.,  6.],
       [ 4.,  6.],
       [ 8.,  6.],
       [18.,  6.],
       [13.,  6.],
       [ 6.,  7.],
       [10.,  7.],
       [19.,  8.],
       [12.,  8.],
       [16.,  9.],
       [15.,  9.],
       [ 0.,  9.],
       [ 5.,  9.],
       [ 2.,  9.],
       [14.,  9.],
       [ 9.,  9.]])

With NumPy, you can inspect the values that satisfy the condition

In [ ]:

data[data[:,1]>8,1] #return all values exceed condition

Function ```where()``` return an array that satisfies the condition:
```
  >>> a = np.arange(10)
  >>> a
  array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
  >>> np.where(a < 5, a, 10*a)
  array([ 0,  1,  2,  3,  4, 50, 60, 70, 80, 90])
```

In [ ]:
np.where(data[:,1]>8) # Get the indices

In [ ]:
data[:,1]

array([9., 6., 9., 6., 6., 9., 7., 5., 6., 9., 7., 5., 8., 6., 9., 9., 9.,
       6., 6., 8.])

# Split NumPy array


In [ ]:
#with random.permutation, return a shuffled array from 0 to n-1
shuffled_indices = np.random.permutation(len(data))

In [ ]:
shuffled_indices

array([ 8,  6, 13, 11, 10,  2,  3, 12, 14,  1, 19, 17,  9,  0,  5, 15, 18,
       16,  7,  4])

In [ ]:
test_set_size = int(len(data)*0.2)
test_set_size

4

In [ ]:
test_indices = shuffled_indices[:test_set_size]
test_indices

array([ 8,  6, 13, 11])

In [ ]:
train_indices = shuffled_indices[test_set_size:]
train_indices

array([10,  2,  3, 12, 14,  1, 19, 17,  9,  0,  5, 15, 18, 16,  7,  4])

In [ ]:
x_train = data[train_indices,:]
x_train

array([[ 8.,  7., 10.],
       [10.,  9.,  7.],
       [ 6.,  6., 10.],
       [ 7.,  8.,  8.],
       [ 7.,  9.,  8.],
       [10.,  6.,  8.],
       [ 8.,  8.,  9.],
       [ 9.,  6.,  7.],
       [ 6.,  9., 10.],
       [ 7.,  9.,  9.],
       [ 8.,  9.,  7.],
       [ 9.,  9.,  9.],
       [ 9.,  6.,  9.],
       [ 6.,  9., 10.],
       [ 7.,  5., 10.],
       [ 8.,  6.,  7.]])

In [ ]:
x_test= data[test_indices,:]
x_test

array([[ 7.,  6., 10.],
       [ 9.,  7.,  9.],
       [ 8.,  6.,  7.],
       [ 6.,  5.,  9.]])

In [ ]:
#Define a function that takes the data and return a dataset for training and other for test
#test_ratio defines the percentage of the size of the test dataset.
def split_train_test(data,test_ratio):
  shuffled_indices = np.random.permutation(len(data))
  test_set_size = int(len(data) * test_ratio)
  test_indices = shuffled_indices[:test_set_size]
  train_indices = shuffled_indices[test_set_size:]
  return data[train_indices,:], data[test_indices,:]

In [ ]:
train,test=split_train_test(data,0.1)

In [ ]:
test

array([[ 8.,  7., 10.],
       [10.,  6.,  8.]])